/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package it.unibo.giocooca;

/** Main application entry-point's class. */

public final class App {
    private App() { }

    /**
     * Main application entry-point.
     *
     * @param args passed to JavaFX.
     */
    public static void main(final String[] args) {
        
    }
}
