/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package it.unibo.giocooca;

import it.unibo.giocooca.navigation.SceneManager;
import it.unibo.giocooca.navigation.impl.SceneManagerImpl;
import javafx.application.Application;
import javafx.stage.Stage;

/**
 * Main application entry-point's class.
 */

public final class App extends Application {
    /**
     * Main application entry-point.
     *
     * @param args passed to JavaFX.
     */
    public static void main(final String[] args) {
        launch(args);
    }

    @Override
    public void start(final Stage primaryStage) {
        final SceneManager sceneManager = new SceneManagerImpl(primaryStage);
        sceneManager.showMenu();
    }
}
